---
# vars file for dnsmasq
dnsmasq_snapd: '/etc/dnsmasq.d'

dnsmasq_domains:
  local:
    options:
      - 'expand-hosts'
      - 'local=/ultimum.dmz/'
      - 'interface=enp2s0f0,virbr0,lo0'
      - 'server=23.19.53.53'
      - 'server=23.19.52.52'
  linux:
    server:
      - '/linux.ultimum.net/192.168.122.10'
      - '/linux.ultimum.net/192.168.122.11'
      - '/10.0.10.in-addr.arpa/192.168.122.10'
      - '/10.0.10.in-addr.arpa/192.168.122.11'
  ultimum:
    server:
      - '/ultimum.net/192.168.122.20'
      - '/20.0.10.in-addr.arpa/192.168.122.20'
...
